const moment = require('moment');

const laughingsquidTweets = { statuses:
    [ { created_at: 'Thu Mar 01 03:03:01 +0000 2018',
        id: 969045315499196400,
        id_str: '969045315499196417',
        text: 'Trying to Play Grand Theft Auto V Without Breaking Any Laws https://t.co/KgBolNtrjs https://t.co/DdoF9np1Sd',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 6,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Thu Mar 01 02:03:06 +0000 2018',
        id: 969030236984705000,
        id_str: '969030236984705024',
        text: 'A Fascinating Series Featuring a Man Methodically Restoring Vintage Hand Tools Without Any Narration… https://t.co/EPHJu6Tgn5',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 1,
        favorite_count: 11,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 23:43:04 +0000 2018',
        id: 968994994899046400,
        id_str: '968994994899046401',
        text: 'Talented Musician Performs \'Prelude in C Minor\' by J.S. Bach on a Beautiful Renaissance Archlute… https://t.co/JbcCvoQCNx',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 5,
        favorite_count: 16,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 23:23:02 +0000 2018',
        id: 968989954972975100,
        id_str: '968989954972975104',
        text: 'Why the Elusive State of Happiness Is More Valuable When It Is Sought Than When It Is Simply Granted… https://t.co/Q1CvzNIwaY',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 2,
        favorite_count: 4,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 23:03:01 +0000 2018',
        id: 968984917458767900,
        id_str: '968984917458767873',
        text: 'A Very Vocal Parrot With a Insatiable Sweet Tooth Continuously Screams for Ice Cream https://t.co/9LnVeOWPB7 https://t.co/wX7g4aZc41',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 5,
        favorite_count: 6,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 22:43:04 +0000 2018',
        id: 968979894259593200,
        id_str: '968979894259593217',
        text: 'A Humorous Look at the Typical Rituals and Habits of the Millennial Generation https://t.co/Hke93GxlCf https://t.co/e16uXRK1W0',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 2,
        favorite_count: 8,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 22:23:02 +0000 2018',
        id: 968974855700930600,
        id_str: '968974855700930560',
        text: 'The Reason Why Ships in World War I Were Painted in Brightly Colored Geometric Dazzle Camouflage… https://t.co/KOiDwkBLhV',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 4,
        favorite_count: 9,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 22:03:10 +0000 2018',
        id: 968969856103141400,
        id_str: '968969856103141377',
        text: 'Russian Photographer Creates Surreal Photo Manipulations Full of Wonder and Imagination https://t.co/5DLK4mKdAE https://t.co/kYYi70XJR0',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 14,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 21:43:01 +0000 2018',
        id: 968964784761851900,
        id_str: '968964784761851904',
        text: 'Majestic Wilderness, A Mysterious and Quirky Animated Journey Into the Shadows of the Jungle https://t.co/6Dq8TmuorG https://t.co/hHcNvE5s75',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 1,
        favorite_count: 3,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 21:23:12 +0000 2018',
        id: 968959794836058100,
        id_str: '968959794836058112',
        text: 'Arnold Schwarzenegger Sings About Bringing it \'Back to the Carpet\' in a \'Kindergarten Cop\' Remix… https://t.co/ACcOr2NQh4',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 3,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 21:03:12 +0000 2018',
        id: 968954762480808000,
        id_str: '968954762480807936',
        text: 'The Incredible Evolving Career of Actress Ann Dowd https://t.co/X4q1TRlPY3 https://t.co/W8OjGGgG6p',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 5,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 20:43:13 +0000 2018',
        id: 968949735808798700,
        id_str: '968949735808798723',
        text: 'Japanese Man With Steady Hands Stacks Coins to Create Gravity Defying Sculptures https://t.co/SDRydOpcEr https://t.co/lhGQbItwdO',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 3,
        favorite_count: 10,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 20:23:07 +0000 2018',
        id: 968944675439640600,
        id_str: '968944675439640577',
        text: 'The World\'s Largest LEGO Ferris Wheel https://t.co/rLIVrKCKUf https://t.co/3FgnrdUisv',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 5,
        favorite_count: 2,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 20:03:06 +0000 2018',
        id: 968939636931416000,
        id_str: '968939636931416064',
        text: 'Dog Photographer William Wegman Opens Up About the Beloved Weimaraners Featured in His Photos… https://t.co/WYZaXWUK5e',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 5,
        favorite_count: 8,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 19:43:09 +0000 2018',
        id: 968934619184881700,
        id_str: '968934619184881666',
        text: 'A Hydraulic Press Cuts a Bowling Ball, a Camera, and Other Random Objects in Half With a Giant Blade… https://t.co/erPWuXJFpe',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 1,
        favorite_count: 5,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 19:23:07 +0000 2018',
        id: 968929576184369200,
        id_str: '968929576184369152',
        text: 'Dolce &amp; Gabbana Send Drones Down the Catwalk to Model New Handbags During Milan Fashion Week https://t.co/al3UE6HxYn https://t.co/Q6AmDD8vG0',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 1,
        favorite_count: 4,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 19:03:06 +0000 2018',
        id: 968924537172742100,
        id_str: '968924537172742144',
        text: 'A Tutorial on Xhosa, A Real South African Language Used as the Language of Wakanda in Black Panther… https://t.co/yADkBZeCQD',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 5,
        favorite_count: 7,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 18:43:09 +0000 2018',
        id: 968919518369239000,
        id_str: '968919518369239040',
        text: 'Wreck-It Ralph Ventures Into Online Culture and Dodges Clickbait in a Trailer for \'Wreck-It Ralph 2\'… https://t.co/pot9rO7FOc',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 2,
        favorite_count: 6,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 18:23:04 +0000 2018',
        id: 968914464815886300,
        id_str: '968914464815886337',
        text: 'Filmmaker Kevin Smith Shares His Experience of Surviving an Unexpected Widow Maker Heart Attack… https://t.co/WtkBg86UdF',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 5,
        favorite_count: 18,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 18:03:03 +0000 2018',
        id: 968909427272245200,
        id_str: '968909427272245248',
        text: 'How to Pick a Padlock Using Lock Picks https://t.co/Y6fKrK7ofc https://t.co/1c4WxBSbD5',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 2,
        favorite_count: 24,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 17:43:08 +0000 2018',
        id: 968904415594860500,
        id_str: '968904415594860544',
        text: 'A Functioning 2x2 Rubik\'s Cube Made Out of Cheddar Cheese https://t.co/y05qjF2hm6 https://t.co/iwgnR5LMOw',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 3,
        favorite_count: 10,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 17:23:04 +0000 2018',
        id: 968899366286131200,
        id_str: '968899366286131200',
        text: 'Fascinating Timelapse of a Cruise Ship Being Built https://t.co/Q00IXeyAUp https://t.co/L1WRMGJ3iW',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 6,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 17:03:05 +0000 2018',
        id: 968894337458364400,
        id_str: '968894337458364416',
        text: 'Wonder Woman Star Gal Gadot Shows Off Her Super Hula Hooping Skills https://t.co/eQ0ibS4GvM https://t.co/JH7jKkNDUt',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 4,
        favorite_count: 14,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 16:03:10 +0000 2018',
        id: 968879256385224700,
        id_str: '968879256385224704',
        text: 'Cute Baby Hangs Onto a Roomba to Take a Ride Around the Kitchen https://t.co/bFoLpTXyEA https://t.co/1Oz5Snpvyx',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 3,
        favorite_count: 12,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 15:03:12 +0000 2018',
        id: 968864166244245500,
        id_str: '968864166244245504',
        text: 'Giant Sharks Attack a Small Submarine While Competing for a Whale Carcass on \'Blue Planet\' https://t.co/M9nWZZao7g https://t.co/Bp0YEzrkQa',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 1,
        favorite_count: 6,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 03:03:07 +0000 2018',
        id: 968682952589807600,
        id_str: '968682952589807616',
        text: 'Brooklyn Photographer Creates Remarkable Images That Encompass a Whimsical Sense of the Surreal… https://t.co/ZZosZtuUYH',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 6,
        favorite_count: 21,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 02:03:04 +0000 2018',
        id: 968667839904256000,
        id_str: '968667839904256000',
        text: 'Artist Adds More Pop Culture Characters and Objects to Old Thrift Store Paintings https://t.co/g8zbBiQOFS https://t.co/sncPElyIgr',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 24,
        favorite_count: 66,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 00:23:04 +0000 2018',
        id: 968642673233064000,
        id_str: '968642673233063939',
        text: 'Lembit Funk Deftly Demonstrates How to Play the Shenanigan, An Ancient, Elegant, Intuitive Instrument… https://t.co/gl0zN5eBSu',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 4,
        favorite_count: 8,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 00:03:01 +0000 2018',
        id: 968637629263745000,
        id_str: '968637629263745025',
        text: 'Gâteau Gato, A Brilliant Purring Cake Zoetrope Dedicated to All Things Cat https://t.co/ZdWVv0bYai https://t.co/d8ENR5R9m5',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 12,
        favorite_count: 28,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Tue Feb 27 23:43:01 +0000 2018',
        id: 968632595339759600,
        id_str: '968632595339759616',
        text: 'A Dutiful Herd of Deer Safely Pause at a Stop Sign Before Crossing a Snowy British Columbia Street… https://t.co/tAk2YMP2J2',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 4,
        favorite_count: 16,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' } ],
   search_metadata:
    { completed_in: 0.059,
      max_id: 969045315499196400,
      max_id_str: '969045315499196417',
      next_results: '?max_id=968632595339759615&q=from%3Alaughingsquid&count=30&include_entities=1',
      query: 'from%3Alaughingsquid',
      refresh_url: '?since_id=969045315499196417&q=from%3Alaughingsquid&include_entities=1',
      count: 30,
      since_id: 0,
      since_id_str: '0' } }


      console.log('we have ', laughingsquidTweets.statuses.length, ' tweets');
      let displayData = laughingsquidTweets.statuses.map((val) =>{
          let output = {
              text: val.text,
              formattedDate: moment(new Date(val.created_at)).format('LLLL'),
              //TODO refactor to take a variable for screen name
              link: `https://twitter.com/${'laughingsquid'}/status/${val.id_str}`
          }
          return output;
      })
      console.log('sample data returns an : ', Array.isArray(displayData), )

module.exports = displayData;