/*
Use this file for prototyping and maybe testing
Data replicates entire response from Twitter API using:

Functions at the end of this file reduce the data to just what needs to be passed to the front end state
*/

const moment = require('moment');
const techcrunch = { statuses:
[ { created_at: 'Fri Mar 02 05:42:04 +0000 2018',
  id: 969447726025986000,
  id_str: '969447726025986049',
  text: '.@Jaguar reveals the new all-electric I-PACE SUV https://t.co/ZSoXoPevSa https://t.co/zhGTyH0AA3',
  truncated: false,
  entities: [Object],
  extended_entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 11,
  favorite_count: 24,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Fri Mar 02 05:14:02 +0000 2018',
  id: 969440673140301800,
  id_str: '969440673140301824',
  text: 'Facebook is ending its short-lived (and misguided) experiment with the alternative news feed feature called “Explor… https://t.co/pqVXecdrDY',
  truncated: true,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 31,
  favorite_count: 43,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Fri Mar 02 04:15:08 +0000 2018',
  id: 969425849593356300,
  id_str: '969425849593356288',
  text: 'How ad-free subscriptions could solve Facebook https://t.co/ricNRbBnnK',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 20,
  favorite_count: 27,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Fri Mar 02 03:26:04 +0000 2018',
  id: 969413502011142100,
  id_str: '969413502011142145',
  text: 'Light is back with a new twist on its anti-smartphone phone https://t.co/2u0j1JK38A',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 32,
  favorite_count: 47,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Fri Mar 02 02:40:07 +0000 2018',
  id: 969401937740386300,
  id_str: '969401937740386304',
  text: 'ClassPass has raised a total of $173 million with a valuation of $470 million https://t.co/M4VYXFp0o1',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 15,
  favorite_count: 28,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Fri Mar 02 01:56:15 +0000 2018',
  id: 969390901184184300,
  id_str: '969390901184184320',
  text: 'Google\'s new YouTube Stories feature lets you swap out your background (no green screen required) https://t.co/kKROmRnH0z',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 46,
  favorite_count: 85,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Fri Mar 02 01:21:04 +0000 2018',
  id: 969382043590254600,
  id_str: '969382043590254592',
  text: 'Astranis emerges from stealth with a new satellite technology for connecting the world https://t.co/420Va5oUWP https://t.co/MLOAkRqJge',
  truncated: false,
  entities: [Object],
  extended_entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 16,
  favorite_count: 20,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Fri Mar 02 01:05:13 +0000 2018',
  id: 969378057176858600,
  id_str: '969378057176858626',
  text: 'Instagram code reveals unreleased voice and video calling https://t.co/1zN1ToARjp by @joshconstine',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 39,
  favorite_count: 51,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Fri Mar 02 00:41:02 +0000 2018',
  id: 969371970067341300,
  id_str: '969371970067341313',
  text: 'Travis Kalanick joins medical tech startup\'s board of directors https://t.co/0z8kosfEHn by @meganrosedickey',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 17,
  favorite_count: 28,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Fri Mar 02 00:06:05 +0000 2018',
  id: 969363175392075800,
  id_str: '969363175392075778',
  text: 'Uber co-founder Garrett Camp is creating a new cryptocurrency https://t.co/0g5krR0Wzl by @fitztepper',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 37,
  favorite_count: 69,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Fri Mar 02 00:04:01 +0000 2018',
  id: 969362656095293400,
  id_str: '969362656095293442',
  text: 'Uber Health’s creation is rooted in the alarming statistics about patient care and healthcare client absentee rates https://t.co/WJhlnNRWsR',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 21,
  favorite_count: 36,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 23:05:00 +0000 2018',
  id: 969347803980890100,
  id_str: '969347803980890113',
  text: 'Caterina Fake on turning down VC roles a decade ago: “I just kind of didn’t fit in” https://t.co/CukZSRLu9r',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 12,
  favorite_count: 22,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 22:42:04 +0000 2018',
  id: 969342031146504200,
  id_str: '969342031146504192',
  text: 'An excerpt from Ryan Holiday’s new book Conspiracy: Peter Thiel, Hulk Hogan, Gawker, and the Anatomy of Intrigue https://t.co/ulAdh5wsqo',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 12,
  favorite_count: 35,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 21:31:07 +0000 2018',
  id: 969324177328103400,
  id_str: '969324177328103424',
  text: 'The top smartphones of MWC 2018 https://t.co/hHQ2JNyUrA #MWC18 https://t.co/oR11kPInTQ',
  truncated: false,
  entities: [Object],
  extended_entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 25,
  favorite_count: 41,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 20:03:48 +0000 2018',
  id: 969302204589813800,
  id_str: '969302204589813761',
  text: 'Facebook\'s next money-maker: Messenger Broadcasts https://t.co/VJYNmV9oTo by @joshconstine',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 29,
  favorite_count: 36,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 20:03:26 +0000 2018',
  id: 969302109727293400,
  id_str: '969302109727293440',
  text: 'Facebook ends its experiment with the alternative "explore" news feed https://t.co/g4ZB7cfyb5 by @jshieber',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 17,
  favorite_count: 23,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 19:55:04 +0000 2018',
  id: 969300004677537800,
  id_str: '969300004677537792',
  text: 'This Dropbox and Google partnership has been in the works for some time https://t.co/KzWzJEwU3S',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 44,
  favorite_count: 59,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 19:19:58 +0000 2018',
  id: 969291173545300000,
  id_str: '969291173545299969',
  text: 'A new sports startup buys VOD platform Colony https://t.co/43mhmjMMjw by @anthonyha',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 16,
  favorite_count: 20,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 19:09:33 +0000 2018',
  id: 969288550876291100,
  id_str: '969288550876291072',
  text: 'Jaguar reveals the new all-electric I-PACE SUV https://t.co/Ye0p4rdAx0 by @etherington',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 22,
  favorite_count: 25,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 19:06:07 +0000 2018',
  id: 969287684693864400,
  id_str: '969287684693864449',
  text: 'Asus’ Zenfone 5 is the king of the MWC iPhone X knockoffs https://t.co/JY9rqvelpU https://t.co/yjn82XZAJ2',
  truncated: false,
  entities: [Object],
  extended_entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 21,
  favorite_count: 38,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 18:28:19 +0000 2018',
  id: 969278172448501800,
  id_str: '969278172448501760',
  text: 'Twitter wants help measuring healthy online interactions https://t.co/EgSBzlTfmz by @meganrosedickey',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 21,
  favorite_count: 25,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 17:42:24 +0000 2018',
  id: 969266618420281300,
  id_str: '969266618420281345',
  text: 'Caterina Fake on turning down VC roles a decade ago: "I just kind of didn\'t fit in" https://t.co/7qEDaYAAvt by @cookie',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 9,
  favorite_count: 20,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 17:32:04 +0000 2018',
  id: 969264017494675500,
  id_str: '969264017494675457',
  text: 'DoorDash joins the unicorn club https://t.co/U3AAjgITrH',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 27,
  favorite_count: 68,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 17:05:27 +0000 2018',
  id: 969257317899391000,
  id_str: '969257317899390976',
  text: 'The dinner that destroyed Gawker https://t.co/p8bTnvmAZc',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 18,
  favorite_count: 42,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 17:05:20 +0000 2018',
  id: 969257290653208600,
  id_str: '969257290653208577',
  text: 'Microsoft advances several of its hosted artificial intelligence algorithms https://t.co/OADudamBMd by @ron_miller',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 31,
  favorite_count: 30,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 17:00:39 +0000 2018',
  id: 969256109340090400,
  id_str: '969256109340090368',
  text: 'Dropbox to add native G Suite integration in new partnership with Google https://t.co/2ljjc50m8o by @ron_miller',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 27,
  favorite_count: 50,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 16:43:08 +0000 2018',
  id: 969251702233759700,
  id_str: '969251702233759744',
  text: '.@Spotify has finally filed to go public, and in doing so the Swedish company has shed light on another huge music… https://t.co/GVDEIlgLXy',
  truncated: true,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 39,
  favorite_count: 69,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 16:14:03 +0000 2018',
  id: 969244384863686700,
  id_str: '969244384863686657',
  text: 'Cloud storage provider Box has started out the day down over 20% on the stock market https://t.co/3IE85EqbL9 $BOX',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 12,
  favorite_count: 17,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 16:06:18 +0000 2018',
  id: 969242432226373600,
  id_str: '969242432226373632',
  text: 'ScopeAI helps companies analyze their customer feedback https://t.co/7MMiUCqHcI by @anthonyha',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 13,
  favorite_count: 20,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' },
{ created_at: 'Thu Mar 01 16:03:48 +0000 2018',
  id: 969241806012547100,
  id_str: '969241806012547072',
  text: 'Graphene-based edible electronics will let you make cereal circuits https://t.co/OOuyPA4pNU by @johnbiggs',
  truncated: false,
  entities: [Object],
  metadata: [Object],
  source: '<a href="http://10up.com" rel="nofollow">10up Publish Tweet</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: [Object],
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 19,
  favorite_count: 41,
  favorited: false,
  retweeted: false,
  possibly_sensitive: false,
  lang: 'en' } ]}



const laughingsquid = { statuses:
    [ { created_at: 'Thu Mar 01 03:03:01 +0000 2018',
        id: 969045315499196400,
        id_str: '969045315499196417',
        text: 'Trying to Play Grand Theft Auto V Without Breaking Any Laws https://t.co/KgBolNtrjs https://t.co/DdoF9np1Sd',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 6,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Thu Mar 01 02:03:06 +0000 2018',
        id: 969030236984705000,
        id_str: '969030236984705024',
        text: 'A Fascinating Series Featuring a Man Methodically Restoring Vintage Hand Tools Without Any Narration… https://t.co/EPHJu6Tgn5',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 1,
        favorite_count: 11,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 23:43:04 +0000 2018',
        id: 968994994899046400,
        id_str: '968994994899046401',
        text: 'Talented Musician Performs \'Prelude in C Minor\' by J.S. Bach on a Beautiful Renaissance Archlute… https://t.co/JbcCvoQCNx',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 5,
        favorite_count: 16,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 23:23:02 +0000 2018',
        id: 968989954972975100,
        id_str: '968989954972975104',
        text: 'Why the Elusive State of Happiness Is More Valuable When It Is Sought Than When It Is Simply Granted… https://t.co/Q1CvzNIwaY',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 2,
        favorite_count: 4,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 23:03:01 +0000 2018',
        id: 968984917458767900,
        id_str: '968984917458767873',
        text: 'A Very Vocal Parrot With a Insatiable Sweet Tooth Continuously Screams for Ice Cream https://t.co/9LnVeOWPB7 https://t.co/wX7g4aZc41',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 5,
        favorite_count: 6,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 22:43:04 +0000 2018',
        id: 968979894259593200,
        id_str: '968979894259593217',
        text: 'A Humorous Look at the Typical Rituals and Habits of the Millennial Generation https://t.co/Hke93GxlCf https://t.co/e16uXRK1W0',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 2,
        favorite_count: 8,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 22:23:02 +0000 2018',
        id: 968974855700930600,
        id_str: '968974855700930560',
        text: 'The Reason Why Ships in World War I Were Painted in Brightly Colored Geometric Dazzle Camouflage… https://t.co/KOiDwkBLhV',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 4,
        favorite_count: 9,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 22:03:10 +0000 2018',
        id: 968969856103141400,
        id_str: '968969856103141377',
        text: 'Russian Photographer Creates Surreal Photo Manipulations Full of Wonder and Imagination https://t.co/5DLK4mKdAE https://t.co/kYYi70XJR0',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 14,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 21:43:01 +0000 2018',
        id: 968964784761851900,
        id_str: '968964784761851904',
        text: 'Majestic Wilderness, A Mysterious and Quirky Animated Journey Into the Shadows of the Jungle https://t.co/6Dq8TmuorG https://t.co/hHcNvE5s75',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 1,
        favorite_count: 3,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 21:23:12 +0000 2018',
        id: 968959794836058100,
        id_str: '968959794836058112',
        text: 'Arnold Schwarzenegger Sings About Bringing it \'Back to the Carpet\' in a \'Kindergarten Cop\' Remix… https://t.co/ACcOr2NQh4',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 3,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 21:03:12 +0000 2018',
        id: 968954762480808000,
        id_str: '968954762480807936',
        text: 'The Incredible Evolving Career of Actress Ann Dowd https://t.co/X4q1TRlPY3 https://t.co/W8OjGGgG6p',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 5,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 20:43:13 +0000 2018',
        id: 968949735808798700,
        id_str: '968949735808798723',
        text: 'Japanese Man With Steady Hands Stacks Coins to Create Gravity Defying Sculptures https://t.co/SDRydOpcEr https://t.co/lhGQbItwdO',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 3,
        favorite_count: 10,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 20:23:07 +0000 2018',
        id: 968944675439640600,
        id_str: '968944675439640577',
        text: 'The World\'s Largest LEGO Ferris Wheel https://t.co/rLIVrKCKUf https://t.co/3FgnrdUisv',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 5,
        favorite_count: 2,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 20:03:06 +0000 2018',
        id: 968939636931416000,
        id_str: '968939636931416064',
        text: 'Dog Photographer William Wegman Opens Up About the Beloved Weimaraners Featured in His Photos… https://t.co/WYZaXWUK5e',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 5,
        favorite_count: 8,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 19:43:09 +0000 2018',
        id: 968934619184881700,
        id_str: '968934619184881666',
        text: 'A Hydraulic Press Cuts a Bowling Ball, a Camera, and Other Random Objects in Half With a Giant Blade… https://t.co/erPWuXJFpe',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 1,
        favorite_count: 5,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 19:23:07 +0000 2018',
        id: 968929576184369200,
        id_str: '968929576184369152',
        text: 'Dolce &amp; Gabbana Send Drones Down the Catwalk to Model New Handbags During Milan Fashion Week https://t.co/al3UE6HxYn https://t.co/Q6AmDD8vG0',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 1,
        favorite_count: 4,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 19:03:06 +0000 2018',
        id: 968924537172742100,
        id_str: '968924537172742144',
        text: 'A Tutorial on Xhosa, A Real South African Language Used as the Language of Wakanda in Black Panther… https://t.co/yADkBZeCQD',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 5,
        favorite_count: 7,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 18:43:09 +0000 2018',
        id: 968919518369239000,
        id_str: '968919518369239040',
        text: 'Wreck-It Ralph Ventures Into Online Culture and Dodges Clickbait in a Trailer for \'Wreck-It Ralph 2\'… https://t.co/pot9rO7FOc',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 2,
        favorite_count: 6,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 18:23:04 +0000 2018',
        id: 968914464815886300,
        id_str: '968914464815886337',
        text: 'Filmmaker Kevin Smith Shares His Experience of Surviving an Unexpected Widow Maker Heart Attack… https://t.co/WtkBg86UdF',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 5,
        favorite_count: 18,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 18:03:03 +0000 2018',
        id: 968909427272245200,
        id_str: '968909427272245248',
        text: 'How to Pick a Padlock Using Lock Picks https://t.co/Y6fKrK7ofc https://t.co/1c4WxBSbD5',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 2,
        favorite_count: 24,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 17:43:08 +0000 2018',
        id: 968904415594860500,
        id_str: '968904415594860544',
        text: 'A Functioning 2x2 Rubik\'s Cube Made Out of Cheddar Cheese https://t.co/y05qjF2hm6 https://t.co/iwgnR5LMOw',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 3,
        favorite_count: 10,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 17:23:04 +0000 2018',
        id: 968899366286131200,
        id_str: '968899366286131200',
        text: 'Fascinating Timelapse of a Cruise Ship Being Built https://t.co/Q00IXeyAUp https://t.co/L1WRMGJ3iW',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 0,
        favorite_count: 6,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 17:03:05 +0000 2018',
        id: 968894337458364400,
        id_str: '968894337458364416',
        text: 'Wonder Woman Star Gal Gadot Shows Off Her Super Hula Hooping Skills https://t.co/eQ0ibS4GvM https://t.co/JH7jKkNDUt',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 4,
        favorite_count: 14,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 16:03:10 +0000 2018',
        id: 968879256385224700,
        id_str: '968879256385224704',
        text: 'Cute Baby Hangs Onto a Roomba to Take a Ride Around the Kitchen https://t.co/bFoLpTXyEA https://t.co/1Oz5Snpvyx',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 3,
        favorite_count: 12,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 15:03:12 +0000 2018',
        id: 968864166244245500,
        id_str: '968864166244245504',
        text: 'Giant Sharks Attack a Small Submarine While Competing for a Whale Carcass on \'Blue Planet\' https://t.co/M9nWZZao7g https://t.co/Bp0YEzrkQa',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 1,
        favorite_count: 6,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 03:03:07 +0000 2018',
        id: 968682952589807600,
        id_str: '968682952589807616',
        text: 'Brooklyn Photographer Creates Remarkable Images That Encompass a Whimsical Sense of the Surreal… https://t.co/ZZosZtuUYH',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 6,
        favorite_count: 21,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 02:03:04 +0000 2018',
        id: 968667839904256000,
        id_str: '968667839904256000',
        text: 'Artist Adds More Pop Culture Characters and Objects to Old Thrift Store Paintings https://t.co/g8zbBiQOFS https://t.co/sncPElyIgr',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 24,
        favorite_count: 66,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 00:23:04 +0000 2018',
        id: 968642673233064000,
        id_str: '968642673233063939',
        text: 'Lembit Funk Deftly Demonstrates How to Play the Shenanigan, An Ancient, Elegant, Intuitive Instrument… https://t.co/gl0zN5eBSu',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 4,
        favorite_count: 8,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Wed Feb 28 00:03:01 +0000 2018',
        id: 968637629263745000,
        id_str: '968637629263745025',
        text: 'Gâteau Gato, A Brilliant Purring Cake Zoetrope Dedicated to All Things Cat https://t.co/ZdWVv0bYai https://t.co/d8ENR5R9m5',
        truncated: false,
        entities: [Object],
        extended_entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 12,
        favorite_count: 28,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' },
      { created_at: 'Tue Feb 27 23:43:01 +0000 2018',
        id: 968632595339759600,
        id_str: '968632595339759616',
        text: 'A Dutiful Herd of Deer Safely Pause at a Stop Sign Before Crossing a Snowy British Columbia Street… https://t.co/tAk2YMP2J2',
        truncated: true,
        entities: [Object],
        metadata: [Object],
        source: '<a href="http://bufferapp.com" rel="nofollow">Buffer</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: [Object],
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 4,
        favorite_count: 16,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: 'en' } ],
   search_metadata:
    { completed_in: 0.059,
      max_id: 969045315499196400,
      max_id_str: '969045315499196417',
      next_results: '?max_id=968632595339759615&q=from%3Alaughingsquid&count=30&include_entities=1',
      query: 'from%3Alaughingsquid',
      refresh_url: '?since_id=969045315499196417&q=from%3Alaughingsquid&include_entities=1',
      count: 30,
      since_id: 0,
      since_id_str: '0' } }

const trizic = { statuses: []};

// Iterate over any of the three 
let formatData = (arr) => {
  if (arr.statuses.length === 0) {
    // return `This account had no tweets in the last week.`
    let output = [{
      text: 'No Tweets found.  Silence.  Nothing.',
      formattedDate: moment().format('LLLL'),
      link: `https://twitter.com/`
    }]
    return output;
  }
  return arr.statuses.map((val) =>{
    let output = {
        text: val.text,
        formattedDate: moment(new Date(val.created_at)).format('LLLL'),
        //TODO refactor to take a variable for screen name
        link: `https://twitter.com/${'anyoldstringwillworkitseems'}/status/${val.id_str}`
    }
    return output;
  })
}

let feeds = {
  trizic: formatData(trizic),
  laughingsquid: formatData(laughingsquid),
  techcrunch: formatData(techcrunch),
}

let fillFeeds = (feedObj) => {
  let keys = [];
  for (let key in feedObj) {
    keys.push(key);
  }
}
fillFeeds(feeds);

module.exports = feeds;